version: '2'
services:
    concourse-db:
        image: postgres:9.5.6
        environment:
            POSTGRES_DB: concourse
            POSTGRES_USER: concourse
            POSTGRES_PASSWORD: changeme
            PGDATA: /database
            shm_size: 1g

    concourse-web:
        image: concourse/concourse
        links: [concourse-db]
        command: web
        ports: ["8080:8080"]
        volumes: ["./keys/web:/concourse-keys"]
        environment:
            CONCOURSE_BASIC_AUTH_USERNAME: concourse
            CONCOURSE_BASIC_AUTH_PASSWORD: changeme
            CONCOURSE_EXTERNAL_URL: http://YOUR_IP_HERE:8080
            CONCOURSE_POSTGRES_DATA_SOURCE: |-
              postgres://concourse:changeme@concourse-db:5432/concourse?sslmode=disable
        dns:
            - 8.8.8.8
            - 8.8.4.4

    concourse-worker:
        image: concourse/concourse
        privileged: true
        links: [concourse-web]
        command: worker
        volumes: ["./keys/worker:/concourse-keys"]
        environment:
            CONCOURSE_TSA_HOST: concourse-web
            CONCOURSE_GARDEN_DNS_SERVER: 8.8.8.8
            CONCOURSE_GARDEN_ADDRESS: concourse-worker
            CONCOURSE_GARDEN_FORWARD_ADDRESS: concourse-worker
            CONCOURSE_BAGGAGECLAIM_FORWARD_ADDRESS: concourse-worker
        dns:
            - 8.8.8.8
            - 8.8.4.4

    docker-registry:
        image: registry:2.6.0
        ports: ["5000:5000"]
